clean:
	./gradlew clean

build:
	./gradlew clean build

run:
	./gradlew run

lint:
	./gradlew checkstyleMain checkstyleTest

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

build-run: build run

.PHONY: build